"""Delete match table

Revision ID: 1ae95303d00d
Revises: a428f8148a86
Create Date: 2023-06-21 13:59:42.565324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ae95303d00d'
down_revision = 'a428f8148a86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_id', table_name='match')
    op.drop_table('match')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('players', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('winner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name='match_game_id_fkey'),
    sa.ForeignKeyConstraint(['winner_id'], ['player.id'], name='match_winner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='match_pkey')
    )
    op.create_index('ix_match_id', 'match', ['id'], unique=False)
    # ### end Alembic commands ###
