"""Make slug not nullable

Revision ID: 597dc95957f4
Revises: 589688e865b5
Create Date: 2023-06-21 14:20:38.407804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597dc95957f4'
down_revision = '589688e865b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
