"""Add status column to match table

Revision ID: d4dafb62e02b
Revises: 597dc95957f4
Create Date: 2023-06-21 20:17:25.717326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4dafb62e02b'
down_revision = '597dc95957f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('status', sa.String(), server_default='IDLE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'status')
    # ### end Alembic commands ###
